apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-delivery-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/techcoms/food-app.git'
    targetRevision: add-frontend
    path: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: food-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
